import type {
  MerchantFoodBill,
  MerchantFoodOrder,
  MerchantFoodPageResult,
  MerchantFoodProduct,
  MerchantFoodRefund,
  MerchantFoodStoreProfile,
} from '@/api/types/merchant-food'
import {
  addMerchantFoodAlbumImage,
  addMerchantFoodStorePhone,
  approveMerchantFoodRefund,
  batchOffShelfMerchantFoodProducts,
  createMerchantFoodProduct,
  deleteMerchantFoodAlbumImage,
  deleteMerchantFoodStorePhone,
  getMerchantFoodAlbumPage,
  getMerchantFoodBillDetail,
  getMerchantFoodBillsPage,
  getMerchantFoodOrderContact,
  getMerchantFoodOrderDetail,
  getMerchantFoodOrdersPage,
  getMerchantFoodProductDetail,
  getMerchantFoodProductsPage,
  getMerchantFoodQualifications,
  getMerchantFoodReconciliationOverview,
  getMerchantFoodRefundDetail,
  getMerchantFoodRefundsPage,
  getMerchantFoodStorePhones,
  getMerchantFoodStoreProfile,
  getMerchantFoodStores,
  rejectMerchantFoodRefund,
  submitMerchantFoodProfileChange,
  updateMerchantFoodEntryImages,
  updateMerchantFoodProduct,
  updateMerchantFoodProductStatus,
  updateMerchantFoodQualifications,
  updateMerchantFoodStoreBusinessStatus,
  updateMerchantFoodStoreCategory,
  updateMerchantFoodStorePhone,
} from '@/api/merchant-food'

// This file is compiled by vue-tsc and keeps the frontend call surface aligned
// with the merchant.food controllers without making network requests.
export const merchantFoodApiContract = {
  getMerchantFoodStores,
  getMerchantFoodStoreProfile,
  updateMerchantFoodStoreBusinessStatus,
  updateMerchantFoodStoreCategory,
  updateMerchantFoodEntryImages,
  submitMerchantFoodProfileChange,
  getMerchantFoodStorePhones,
  addMerchantFoodStorePhone,
  updateMerchantFoodStorePhone,
  deleteMerchantFoodStorePhone,
  getMerchantFoodQualifications,
  updateMerchantFoodQualifications,
  getMerchantFoodAlbumPage,
  addMerchantFoodAlbumImage,
  deleteMerchantFoodAlbumImage,
  getMerchantFoodProductsPage,
  getMerchantFoodProductDetail,
  createMerchantFoodProduct,
  updateMerchantFoodProduct,
  updateMerchantFoodProductStatus,
  batchOffShelfMerchantFoodProducts,
  getMerchantFoodOrdersPage,
  getMerchantFoodOrderDetail,
  getMerchantFoodOrderContact,
  getMerchantFoodRefundsPage,
  getMerchantFoodRefundDetail,
  approveMerchantFoodRefund,
  rejectMerchantFoodRefund,
  getMerchantFoodReconciliationOverview,
  getMerchantFoodBillsPage,
  getMerchantFoodBillDetail,
}

type ContractResponses = [
  MerchantFoodStoreProfile,
  MerchantFoodPageResult<MerchantFoodProduct>,
  MerchantFoodPageResult<MerchantFoodOrder>,
  MerchantFoodPageResult<MerchantFoodRefund>,
  MerchantFoodPageResult<MerchantFoodBill>,
]

export type { ContractResponses }
